GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('coagulation_tank')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setProgressBar(GuiTextures.PROGRESS_BAR_BATH, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('coagulation_tank', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('coagulation_tank')
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
           .aisle('F F', 'CCC', 'CCC', 'CCC')
           .aisle('   ', 'CCC', 'C C', 'CGC')
           .aisle('F F', 'CCC', 'C@C', 'CCC')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('F', Predicates.blocks('gtceu:steel_frame'))
            .where('C', Predicates.blocks('gtceu:solid_machine_casing').setMinGlobalLimited(18)
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)))
            .where('G', Predicates.blocks('minecraft:glass'))
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_solid_steel", 'gtceu:block/machines/mixer')
})