GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('sterling_engine')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(1, 0, 0, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_BATH, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('sterling_engine', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('sterling_engine')
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
           .aisle('CCC', 'CGC', ' F ', '   ')
           .aisle('CCC', 'GHG', 'FHF', ' F ')
           .aisle('CCC', 'C@C', ' F ', '   ')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('F', Predicates.blocks('gtceu:steel_frame'))
            .where('C', Predicates.blocks('gtceu:solid_machine_casing').setMinGlobalLimited(10)
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(2)))
            .where('G', Predicates.blocks('minecraft:glass'))
            .where('H', Predicates.blocks('minecraft:hopper'))
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_solid_steel", 'gtceu:block/machines/electric_furnace')
})