#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 09 19:14:13 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
