#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 03 21:50:31 WET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
