#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 01 23:53:18 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
